require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe LatestMatchesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # LatestMatch. As you add validations to LatestMatch, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LatestMatchesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all latest_matches as @latest_matches" do
      latest_match = LatestMatch.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:latest_matches)).to eq([latest_match])
    end
  end

  describe "GET #show" do
    it "assigns the requested latest_match as @latest_match" do
      latest_match = LatestMatch.create! valid_attributes
      get :show, {:id => latest_match.to_param}, valid_session
      expect(assigns(:latest_match)).to eq(latest_match)
    end
  end

  describe "GET #new" do
    it "assigns a new latest_match as @latest_match" do
      get :new, {}, valid_session
      expect(assigns(:latest_match)).to be_a_new(LatestMatch)
    end
  end

  describe "GET #edit" do
    it "assigns the requested latest_match as @latest_match" do
      latest_match = LatestMatch.create! valid_attributes
      get :edit, {:id => latest_match.to_param}, valid_session
      expect(assigns(:latest_match)).to eq(latest_match)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new LatestMatch" do
        expect {
          post :create, {:latest_match => valid_attributes}, valid_session
        }.to change(LatestMatch, :count).by(1)
      end

      it "assigns a newly created latest_match as @latest_match" do
        post :create, {:latest_match => valid_attributes}, valid_session
        expect(assigns(:latest_match)).to be_a(LatestMatch)
        expect(assigns(:latest_match)).to be_persisted
      end

      it "redirects to the created latest_match" do
        post :create, {:latest_match => valid_attributes}, valid_session
        expect(response).to redirect_to(LatestMatch.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved latest_match as @latest_match" do
        post :create, {:latest_match => invalid_attributes}, valid_session
        expect(assigns(:latest_match)).to be_a_new(LatestMatch)
      end

      it "re-renders the 'new' template" do
        post :create, {:latest_match => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested latest_match" do
        latest_match = LatestMatch.create! valid_attributes
        put :update, {:id => latest_match.to_param, :latest_match => new_attributes}, valid_session
        latest_match.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested latest_match as @latest_match" do
        latest_match = LatestMatch.create! valid_attributes
        put :update, {:id => latest_match.to_param, :latest_match => valid_attributes}, valid_session
        expect(assigns(:latest_match)).to eq(latest_match)
      end

      it "redirects to the latest_match" do
        latest_match = LatestMatch.create! valid_attributes
        put :update, {:id => latest_match.to_param, :latest_match => valid_attributes}, valid_session
        expect(response).to redirect_to(latest_match)
      end
    end

    context "with invalid params" do
      it "assigns the latest_match as @latest_match" do
        latest_match = LatestMatch.create! valid_attributes
        put :update, {:id => latest_match.to_param, :latest_match => invalid_attributes}, valid_session
        expect(assigns(:latest_match)).to eq(latest_match)
      end

      it "re-renders the 'edit' template" do
        latest_match = LatestMatch.create! valid_attributes
        put :update, {:id => latest_match.to_param, :latest_match => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested latest_match" do
      latest_match = LatestMatch.create! valid_attributes
      expect {
        delete :destroy, {:id => latest_match.to_param}, valid_session
      }.to change(LatestMatch, :count).by(-1)
    end

    it "redirects to the latest_matches list" do
      latest_match = LatestMatch.create! valid_attributes
      delete :destroy, {:id => latest_match.to_param}, valid_session
      expect(response).to redirect_to(latest_matches_url)
    end
  end

end
